service: aws-nodejs # NOTE: update this with your service name
package:
  exclude:
    - secrets.yml
provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: trello-call-back
          method: head
      - http:
          path: trello-call-back
          method: post
    environment:
      CHATWORK_API_TOKEN: ${ssm:CHATWORK_API_TOKEN}
      CHATWORK_ROOM_ID: ${ssm:CHATWORK_ROOM_ID}
